### ISSUE TITLE
Implement form to register new users

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biokey#1]
## 📜 Describe the Requirement

BioKey shall have a form similar to [this Google form](https://docs.google.com/forms/d/1_sGaae2YjBlo42b_2idzisqWY6CyPBtpF1-cxcNyhCI/edit) to support registration of new users.

A newly registered user should send a notification to the IC team.

The system shall provide a way to approve or deny registration.

## ☑️ Success Criteria

Replace this text by answering the question: if the software satisfies the requirement, how would you know? You can use GitHub check boxes (i.e., `- [ ] box label`) if you like.

## 〽️ Alternative Ideas

Replace this text with a description of any alternative solutions or features you've considered.

## 🗺 Context

Requested by @hoodriverheather

**Comment by hoodriverheather** [comment]
@nutjob4life To clarify - we need a way to review user registrations to either approve or deny. It doesn't need to be complicated. The form should allow the requester to complete and then send a notification to IC team, we review the email and determine -> allow or deny. I don't think it needs to be too complicated. WDYT?

**Comment by nutjob4life** [comment]
@hoodriverheather it doesn't sound complicated  to me

**Comment by nutjob4life** [comment]
Workflow

1.  User visits the form and fills in name (first name, last name as separate fields)
2.  Check if the user already has an account by searching LDAP for `sn` (surname) and `cn` (common name)
    -   If found and user is a DMCC account, let the user know with links on how to reset password
    -   If found and user is an IC account, let the user know with different links on how to reset password
    -   If not found, go to next step
3.  Ask for remaining details as on the Google form
4.  Mail a link to the user to validate the account
5.  User clicks link in email, sets password
6.  Check password for strength (but allow user to override) — optional? Maybe 2.0
7.  Save password in LDAP
8. Provide "next steps" such as "Visit LabCAS and log in"

**Comment by nutjob4life** [comment]
@hoodriverheather this is ready to try out.

1. Please visit the [dev instance of BioKey](https://labcas-dev.jpl.nasa.gov/biokey/) and choose a consortium to try out, EDRN, MCL, or NIST.

👉 **Note:** End-users won't see this screen. Instead, each instance of LabCAS will link directly to one of the consortium pages. For example, `edrn-labcas.jpl.nasa.gov` will link directly to `https://labcas-dev.jpl.nasa.gov/biokey/edrn/`.

2. Click the "Sign Up" card or its button and fill in a name. Try names that you know already exist in the consortium or brand new names. Fill in the remaining details, CAPTCHA, etc.
3. See if that new user gets a link to set their password in their email. Try clicking the link and setting the password.
4. See if the members of the `ic-accounts` group gets an email with a notification that the new user was created. Try approving the user, rejecting the user, or deleting the user.

## Testing the Password

Once you've followed the link to set the new user's password, see if it works by trying to log in to one of the corresponding consortium's applications. Alternatively, you can do enter this in the Terminal:

    ldapsearch -x -W -D DN -H ldaps://edrn-ds.jpl.nasa.gov -b BASE -s one '(uid=USERNAME)'

where `DN` is the distinguished name of the new user and takes form:

- `uid=USERNAME,dc=edrn,dc=jpl,dc=nasa,dc=gov` for EDRN
- `uid=USERNAME,ou=users,o=MCL` for MCL
- `uid=USERNAME,ou=users,o=NIST` for NIST

and `BASE` is the base node of all users in the tree and takes the form:

- `dc=edrn,dc=jpl,dc=nasa,dc=gov` for EDRN
- `ou=users,o=MCL` for MCL
- `ou=users,o=NIST` for NIST

and `USERNAME` is the new user's username. You'll be prompted for the password; enter the newly set one to see if it works.


## Deleting Extraneous Users

As you test, you may start to create lots of extra users. To delete them, _very carefully_ enter this command into a Terminal prompt:

    ldapdelete -x -W -D uid=admin,ou=system -H ldaps://edrn-ds.jpl.nasa.gov DN [DN…]

Where `DN` is a distinguished name of the user to delete. You can provide multiple DNs on the command-line. You'll be prompted for the LDAP admin password; enter it.

⚠️ **Never** put in a DN without the `uid=USERNAME` part! For example, if you use `ou=users,o=NIST` as the DN, you will delete every single user in NIST!

**Comment by hoodriverheather** [comment]
@nutjob4life This is great. There's this text I think we need to add for users to let them know they need to wait until they receive the approval email.
<img width="1285" alt="Screenshot 2024-06-25 at 11 57 44 AM" src="https://github.com/EDRN/biokey/assets/58526347/52adbdfd-61b7-4dc9-89da-408ad866c52a">

For NIST. I think we will need to know which LDAP groups they should belong in and there's an approval process with NIST. Maybe it won't be as automated? We can discuss more on that after we get the EDRN figured out.

**Comment by nutjob4life** [comment]
@hoodriverheather okay, I have changed the page template to use the wording in the [screenshot in this comment]().

I've also changed the email notice to end users to read as follows:
```
Hello!

Your account, "{uid}", has been created for the {consortium}. Two things to be aware of:

1. Your account is in the "pending" state. An administrator will review the account
and may approve or reject it. Until it's approved, you won't have access to data or
resources.

2. While you're waiting, you can go ahead and set the password for this account.
To do so, you'll need to visit the following link within {natural_delta}:

{link}

This link will expire on {expiration_time} (UTC). If you can't visit the link in that time,
visit {url} and choose the "Forgotten password" option for a fresh link.

Thank you.
```

This is now live on [the dev instance of BioKey](https://labcas-dev.jpl.nasa.gov/biokey/)

**Comment by hoodriverheather** [comment]
@nutjob4life 
For the EDRN Sign Up form. I think it would be good to be clear that users are applying for an EDRN LabCAS Account. What do you think about changing the title of this form to Apply for an EDRN LabCAS Account? See screenshot below.
<img width="1110" alt="Screenshot 2024-06-26 at 3 08 46 PM" src="https://github.com/EDRN/biokey/assets/58526347/0f0b8f82-a390-4b93-896e-eb393be4538b">

**Comment by nutjob4life** [comment]
Okie doke, can do

**Comment by nutjob4life** [comment]
This is now live on [the dev site](https://labcas-dev.jpl.nasa.gov/biokey/)
