### ISSUE TITLE
Web app look-and-feel (theme)

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biokey#4]
## 📜 Describe the Requirement

The EDRN LabCAS profile app (user registration and password change) should adhere to a certain look-and-feel, or "theme". 

Possible themes:

- [JPL public website theme, similar to the Data Science website](https://datascience.jpl.nasa.gov/)
- [EDRN portal theme](https://edrn.nci.nih.gov/)
- [Existing LabCAS UI theme](https://edrn-labcas.jpl.nasa.gov/)
- Something else

Regardless, [Bootstrap](https://getbootstrap.com/) should be used as a base due to its wide array of widgets, layout support, and mobile-friendliness.

@hoodriverheather: what should the theme be?

## ☑️ Success Criteria

This is subjective, of course, but if anything it should look like a "well dressed" website and not plain, un-styled HTML.

## 〽️ Alternative Ideas

FYI, there's a [nice collection of other themes](https://themes.getbootstrap.com) out there.

**Comment by hoodriverheather** [comment]
@nutjob4life Good question. I think we need to ask Dan. Initially i would say the Existing LabCAS UI theme. Is this going to be used by just EDRN? Is it also available via NIST?

**Comment by nutjob4life** [comment]
@hoodriverheather okay, assigned to @dcrichto1 to answer.

As for availability, I'm keeping it neutral. It could be used for NIST.

**Comment by nutjob4life** [comment]
@dcrichto1 mentioned in our 2024-06-11 status meeting that he'd like the EDRN look and feel, so that's what I'll do

**Comment by nutjob4life** [comment]
@hoodriverheather to test this … well, it's kind of subjective.

Visit [the EDRN BioKey page](https://labcas-dev.jpl.nasa.gov/biokey/edrn/) and ask: does it look like EDRN?

**Comment by hoodriverheather** [comment]
@nutjob4life Looks great!
