### ISSUE TITLE
Password Strength requirements

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biokey#5]
## 🤔 Tell Us About the Feature

According to our status meeting on 2024-06-11, @dcrichto1 said that enforcing password strength should be an immediate requirement.

## 🎇 What Solution You'd Like

At a minimum, the complexity of a password should be enforced when a user attempts to change or reset a password.

As a bonus, a real-time meter showing the complexity as a user types the password would be nice.

**Comment by nutjob4life** [comment]
@hoodriverheather to test this, use any of the following:

- The initial password set link (for a new account) or the reset link (using the "forgotten password") feature, sent by email
- The change password form, accessed directly in the browser

…and try to create a short, simple, password. Upon submitting the form, you should get a validation error saying the password is too weak.

The password requirements I've arbitrarily set are:

- Must be a passphrase 20 characters or longer
- If 19 characters or shorter, then it must have an upper case letter, a lower case letter, a digit, and a special symbol

Version 2.0 we can try to put in an interactive strength meter.

**Comment by hoodriverheather** [comment]
@nutjob4life I tested and this works great!
