### ISSUE TITLE
Forgotten Details Form

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biokey#7]
## 🤔 Tell Us About the Feature

BioKey shall implement a feature whereby a user who forgets their password can reset it.

In addition, users sometimes even forget their usernames, so BioKey shall implement a feature whereby a user who forgets their username can get it back from the email address.

## 🎇 What Solution You'd Like

This is a little tricky because:

- It's "information leakage" if a hacker can try out a username and be told that the email is on the way versus the username is unknown; we can't do that
- The same applies to an email address: there should be no feedback if the email address is known or unknown
- For EDRN only, some usernames are "secure" site accounts; these should not get an email with a reset-password link but instead go to the DMCC

**Comment by nutjob4life** [comment]
@hoodriverheather to test this, visit the consortium page [in BioKey](https://labcas-dev.jpl.nasa.gov/biokey/) that you wish to test and click the "Forgotten Account" button and/or card.

### Forgotten Password

1. Fill in a known user ID and ensure the inbox for that account gets an email with a link to reset the password for that account. Try clicking the link and changing the password à la #3 and see if the old password stops working and the new password starts working.
2. **For EDRN only**, fill in a known secure site user ID and ensure the inbox for that account gets an email with a link to the DMCC instead
3. Fill in an unknown, bogus user ID and ensure the user interface says the same thing as it did for step 1, not letting on that the username is unknown

### Forgotten Account Name

1. Fill in a known email address and ensure the inbox for that account gets an email with the username in it
2. Fill in an unknown email address and ensure the user interface says the same thing as in step 1

**Comment by nutjob4life** [comment]
Based on a [comment](https://github.com/EDRN/biokey/issues/3#issuecomment-2204083417) from @hoodriverheather, I've made the change to support #7, which puts the two fields next to each other with a large "OR" between them

In small-screen mode, the fields are aligned top-to-bottom with the "OR" in the middle

**Comment by hoodriverheather** [comment]
@nutjob4life Perfect!
